/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.professor;

import View.Menu;

/**
 *
 * @author guilherme
 */
public class MenuProfessor extends javax.swing.JDialog {

    /**
     * Creates new form MenuProfessor
     */
    public MenuProfessor() {
        initComponents();
        setLocation(300, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCadastroProf = new javax.swing.JButton();
        btnMenuBack = new javax.swing.JButton();
        btnExibirCursoProf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Professor");
        jLabel1.setMaximumSize(new java.awt.Dimension(130, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(130, 29));

        btnCadastroProf.setText("Cadastrar Professor");
        btnCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroProfActionPerformed(evt);
            }
        });

        btnMenuBack.setText("Menu");
        btnMenuBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBackActionPerformed(evt);
            }
        });

        btnExibirCursoProf.setText("Exibir Cursos do Professor");
        btnExibirCursoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirCursoProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMenuBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastroProf)
                            .addComponent(btnExibirCursoProf))
                        .addGap(0, 247, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnCadastroProf)
                .addGap(70, 70, 70)
                .addComponent(btnExibirCursoProf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(btnMenuBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProfActionPerformed
        dispose();
        CadastrarProfessor cadastroprofessor = new CadastrarProfessor();
        cadastroprofessor.setVisible(true);
        cadastroprofessor.setLocation(300,100);
        cadastroprofessor.setResizable(false);
        
    }//GEN-LAST:event_btnCadastroProfActionPerformed

    private void btnMenuBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBackActionPerformed
        dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocation(300, 100);
        menu.setResizable(false);
        
        
    }//GEN-LAST:event_btnMenuBackActionPerformed

    private void btnExibirCursoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirCursoProfActionPerformed
        dispose();
        ExibirCursoprofessor exibircursoprofessor = new ExibirCursoprofessor();
        exibircursoprofessor.setVisible(true);
        exibircursoprofessor.setLocation(300, 100);
        exibircursoprofessor.setResizable(false);
    }//GEN-LAST:event_btnExibirCursoProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProfessor().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroProf;
    private javax.swing.JButton btnExibirCursoProf;
    private javax.swing.JButton btnMenuBack;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
